//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarraLeather
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int prodid { get; set; }
        public int cantidad { get; set; }
        public int pedidoid { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual pedidosex pedidosex { get; set; }
        public virtual productos productos { get; set; }
        public virtual users users { get; set; }
    }
}
