//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarraLeather
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidosex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidosex()
        {
            this.pedidos = new HashSet<pedidos>();
        }
    
        public int id { get; set; }
        public int userid { get; set; }
        public decimal subtotal { get; set; }
        public decimal impuesto { get; set; }
        public decimal montoEntrega { get; set; }
        public int estatus { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fechadepago { get; set; }
        public int mododepago { get; set; }
        public string direccionEntrega { get; set; }
        public Nullable<decimal> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos> pedidos { get; set; }
    }
}
