//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarraLeather
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<float> precio { get; set; }
        public string descripcion { get; set; }
        public Nullable<float> inventario { get; set; }
        public string foto { get; set; }
        public Nullable<int> status { get; set; }
        public string category { get; set; }
        public Nullable<int> categoryid { get; set; }
    }
}
